[package]
name = "better-twitter-archiver-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {features=["pure"]}
twitter-v2 = "0.1.4"
reqwest = "0.11.10"
ron = "0.7.0"
time = "0.3.9"